server:
  port: 8762

eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://pomelo:pomelo@peer1:8761/eureka/

spring:
  application:
    name: eureka-server
  security:
    basic:
      enabled: true
    user:
      name: pomelo
      password: pomelo
