server:
  port: 8761

eureka:
  instance:
    # C:\Windows\System32\drivers\etc\hosts(Windows) | /etc/hosts(Linux)
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server
