server:
  port: 8760

eureka:
  instance:
    # C:\Windows\System32\drivers\etc\hosts(Windows) | /etc/hosts(Linux)
    # hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: eureka-server
  security:
    basic:
      enabled: true
    user:
      name: pomelo
      password: pomelo