server:
   port: 8100
eureka:
   client:
      serviceUrl:
         defaultZone: http://pomelo:pomelo@localhost:8760/eureka/
   instance:
      prefer-ip-Address: true
spring:
   profiles:
      active: dev
   application:
      name: pomelo-user-server
   http:
      encoding:
         charset: UTF-8
         enabled: true
         force: true
      multipart:
         max-file-size: 10M
         max-request-size: 20M
         defaultEncoding: UTF-8
logging:
   config: classpath:logback-spring.xml
   path: logs